analytics/urls.py
from django.conf.urls import url
from . import views
#from django.conf.urls import *
#from django.contrib.auth import views as auth_views
#from django.views.generic import TemplateView
urlpatterns = [
    url(r'^chart/', views.ChartView, name='chart'),
    url(r'^segments', views.SegmentView, name='segment'),
    ] 

api/urls.py
from django.conf.urls import url, include
from rest_framework import routers
from api import views as api_views

urlpatterns = [
    url(r'^incidents/sources/list/', api_views.SourceList.as_view(), name='list_sources'),
    #url(r'^incidents/sources/add/', api_views.SourceCreate.as_view(), name='create_new_source'),
    url(r'^incidents/create/', api_views.IncidentCreate.as_view(), name='create_new_incident'),
    url(r'^incidents/update/', api_views.IncidentUpdate.as_view(), name='update_incident'),
    url(r'^incidents/list/start/', api_views.IncidentStartList.as_view(), name='start_list_incidents'),
    url(r'^incidents/list/name/(?P<inc_name>[a-zA-Z0-9w@%.-]+)/', api_views.IncidentSearchNameList.as_view(), name='searc_name_list_incidents'),
    url(r'^incidents/list/id/(?P<inc_id>[0-9]+)/', api_views.IncidentSearchIdList.as_view(), name='searc_id_list_incidents'),
    url(r'^incidents/data/(?P<inc_id>[0-9]+)/', api_views.GetIncindentData.as_view(), name='get_incident_data'),
    url(r'^manage_db/incidents/weeks/(?P<start_date>\d{4}-\d{2}-\d{2})/(?P<end_date>\d{4}-\d{2}-\d{2})/', api_views.MdbIncindentsFilterWeeks.as_view(), name='mdb_filter_weeks_incident'),
    url(r'^incidents/touched/(?P<inc_id>[0-9]+)/', api_views.GetIncindentToucheData.as_view(), name='get_incident_touch_data'),
    url(r'^incidents/descriptionTetxt/(?P<inc_id>[0-9]+)/', api_views.GetIncindentDescriptionData.as_view(), name='get_incident_description_data'),
    url(r'^incidents/assigned/(?P<inc_id>[0-9]+)/', api_views.GetIncindentAssignedData.as_view(), name='get_incident_assigned_data'),
    url(r'^manage_db/create_descriptions_workspace/', api_views.CreateDescriptionsWorkspace.as_view(), name='create_descriptions_workspace'),
    url(r'^manage_db/create_assigned_entry/', api_views.CreateAssignedEntry.as_view(), name='create_assigned_entry'),
    url(r'^manage_db/startEntries/', api_views.GetStartEntries.as_view(), name='get_start_entries'),
    url(r'^manage_db/entries/name/(?P<entry_name>[a-zA-Z0-9w@%.-]+)/', api_views.FilterEntryName.as_view(), name='filter_entry_name'),
    url(r'^manage_db/entries/key/(?P<entry_name>[a-zA-Z0-9w@%.-]+)/', api_views.FilterEntryKey.as_view(), name='filter_entry_key'),
    url(r'^manage_db/entries/id/(?P<entry_id>[0-9]+)/', api_views.FilterEntryId.as_view(), name='filter_entry_id'),
    url(r'^manage_db/entries/date/(?P<entry_date>\d{4}-\d{2}-\d{2})/', api_views.FilterEntryDate.as_view(), name='filter_entry_date'),
    url(r'^manage_db/delete_entry/', api_views.DeleteEntry.as_view(), name='delete_entry'),
    url(r'^manage_db/create_new_entry/', api_views.CreateNewEntry.as_view(), name='create_new_entry'),
    url(r'^manage_db/entry/(?P<entry_id>[0-9]+)/mainInfo/', api_views.EntryData_MainInfo.as_view(), name='entry_data_main_info'),
    url(r'^manage_db/entry/(?P<entry_id>[0-9]+)/values/(?P<value_id>[0-9]+)', api_views.EntryData_ValueInfo.as_view(), name='entry_data_value_info'),
    url(r'^manage_db/entry/(?P<entry_id>[0-9]+)/reports/', api_views.EntryData_ReportsData.as_view(), name='entry_data_reports'),
    url(r'^manage_db/victims/allChoices/', api_views.VictimsData_All.as_view(), name='victims_data_all'),
    #url(r'^manage_db/update_entry/victims/', api_views.EntryDataUpdate_victims.as_view(), name='entry_data_update_victims'),
    url(r'^manage_db/update_entry/name/', api_views.EntryDataUpdate_name.as_view(), name='entry_data_update_name'),
    url(r'^manage_db/update_entry/remarks/', api_views.EntryDataUpdate_remarks.as_view(), name='entry_data_update_remarks'),
    url(r'^manage_db/update_entry/summary/', api_views.EntryDataUpdate_Summary.as_view(), name='entry_data_update_summary'),
    url(r'^manage_db/update_entry/comments/', api_views.EntryDataUpdate_comments.as_view(), name='entry_data_update_comments'),
    url(r'^manage_db/update_entry/unassign_description/', api_views.EntryDataUpdate_desc_unassigns.as_view(), name='entry_data_update_int_description_unassigns'),
    url(r'^manage_db/update_entry/information_grading/', api_views.EntryDataUpdate_infGrading.as_view(), name='entry_data_update_info_grading'),
    #url(r'^manage_db/update_entry/new_information_grading/', api_views.EntryDataUpdate_NewinfGrading.as_view(), name='entry_data_update_new_info_grading'),
    url(r'^manage_db/update_entry/nature_main_group/', api_views.EntryDataUpdate_NatureMainGroup.as_view(), name='entry_data_update_nature_main_group'),#remove
    url(r'^manage_db/update_entry/nature_sub_group/', api_views.EntryDataUpdate_NatureSubGroup.as_view(), name='entry_data_update_nature_sub_group'),#remove
    url(r'^manage_db/update_entry/nature_add/', api_views.EntryDataUpdate_NatureAdd.as_view(), name='entry_data_update_nature_add'),
    url(r'^manage_db/update_entry/nature_remove/', api_views.EntryDataUpdate_NatureRemove.as_view(), name='entry_data_update_nature_remove'),
    #url(r'^manage_db/update_entry/new_nature_main/', api_views.EntryDataUpdate_NewNatureMain.as_view(), name='entry_data_update_new_nature_main'),
    #url(r'^manage_db/update_entry/new_nature_sub/', api_views.EntryDataUpdate_NewNatureSub.as_view(), name='entry_data_update_new_nature_sub'),
    url(r'^manage_db/update_entry/victims_add/', api_views.EntryDataUpdate_VictimAdd.as_view(), name='entry_data_update_victim_add'),
    url(r'^manage_db/update_entry/victims_remove/', api_views.EntryDataUpdate_VictimRemove.as_view(), name='entry_data_update_victim_remove'),
    #url(r'^manage_db/update_entry/victim_add/', api_views.EntryDataUpdate_NewVictim.as_view(), name='entry_data_update_new_victim'),
    url(r'^manage_db/update_entry/victims_num/', api_views.EntryDataUpdate_VictimsNum.as_view(), name='entry_data_update_victims_num'),#remove
    url(r'^manage_db/update_entry/actors_add/', api_views.EntryDataUpdate_ActorAdd.as_view(), name='entry_data_actor_add'),
    url(r'^manage_db/update_entry/actors_remove/', api_views.EntryDataUpdate_ActorRemove.as_view(), name='entry_data_actor_remove'),
    url(r'^manage_db/update_entry/document_upload/$', api_views.UploadFile.as_view({'get': 'list', 'post':'create',}), name='entry_data_update_document_upload'),
    url(r'^manage_db/update_entry/upload_assigne/$', api_views.UploadAssigne.as_view(), name='entry_data_update_document_upload_assigne'),
    url(r'^manage_db/update_entry/newLink/', api_views.CreateNewLink.as_view(), name='entry_data_update_create_new_link'),
    url(r'^manage_db/update_entry/createValue/', api_views.CreateNewValue.as_view(), name='entry_data_update_create_new_value'),
    url(r'^manage_db/update_entry/deleteValue/', api_views.DeleteValue.as_view(), name='entry_data_update_delete_value'),
    #url(r'^manage_db/update_entry/new_actor/', api_views.EntryDataUpdate_newActor.as_view(), name='entry_data_update_new_actor'),
    url(r'^manage_db/update_entry/location_add/', api_views.EntryDataUpdate_locationAdd.as_view(), name='entry_data_location_add'),
    url(r'^manage_db/update_entry/location_remove/', api_views.EntryDataUpdate_locationRemove.as_view(), name='entry_data_location_remove'),
    #url(r'^manage_db/update_entry/new_region/', api_views.EntryDataUpdate_newRegion.as_view(), name='entry_data_update_new_region'),
    #url(r'^manage_db/update_entry/new_locality/', api_views.EntryDataUpdate_newLocality.as_view(), name='entry_data_update_new_locality'),
    #url(r'^manage_db/update_entry/new_village/', api_views.EntryDataUpdate_newVillage.as_view(), name='entry_data_update_new_village'),
    url(r'^manage_db/update_entry/coordinates/', api_views.EntryDataUpdate_coordinates.as_view(), name='entry_data_update_coordinates'),
    url(r'^manage_db/update_entry/assign_new_description/', api_views.EntryDataUpdate_assignNewDescription.as_view(), name='entry_data_update_assign_new_description'),
    url(r'^manage_db/update_entry/date/', api_views.EntryDataUpdate_date.as_view(), name='entry_data_update_date'),
    url(r'^manage_db/update_entry/time/', api_views.EntryDataUpdate_time.as_view(), name='entry_data_update_time'),
    # hendle load db_data requests
    url(r'^manage_db/db_data/information_grading/', api_views.DBData_infGrading.as_view(), name='db_data_information_grading'),
    url(r'^manage_db/db_data/nature_main/', api_views.DBData_natureMain.as_view(), name='db_data_nature_main'),
    url(r'^manage_db/db_data/nature_sub/(?P<main_id>[0-9]+)/', api_views.DBData_natureSub.as_view(), name='db_data_nature_sub'),
    url(r'^manage_db/db_data/actors/', api_views.DBData_actors.as_view(), name='db_data_actors'),
    url(r'^manage_db/db_data/locations/', api_views.DBData_locations.as_view(), name='db_data_locations'),
    url(r'^manage_db/db_data/locality/(?P<loc_id>[0-9]+)/', api_views.DBData_locality.as_view(), name='db_data_localitys'),
    url(r'^manage_db/db_data/village/(?P<reg_id>[0-9]+)/(?P<loc_id>[0-9]+)/', api_views.DBData_villages.as_view(), name='db_data_villages'),
    url(r'^manage_db/db_data/coordinates/(?P<reg_id>[0-9]+)/(?P<loc_id>[0-9]+)/(?P<vil_id>[0-9]+)/', api_views.DBData_coorsinates.as_view(), name='db_data_coordinates'),
    #url(r'^manage_db/db_data/searc/region/(?P<reg_id>[0-9]+)/(?P<loc_name>[a-zA-Z0-9]+)/', api_views.DBData_searchLocation.as_view(), name='db_data_search_locations'),
    #url(r'^manage_db/db_data/searc/village/(?P<reg_id>[0-9]+)/(?P<loc_id>[0-9]+)/(?P<loc_name>[a-zA-Z0-9]+)/', api_views.DBData_searchVillage.as_view(), name='db_data_search_village'),

    # segments urls
    url(r'^segment/startEntries/', api_views.SegmentsStart.as_view(), name='get_start_segments_entries'),
    url(r'^segment/downloadPreset/(?P<segment_id>[0-9]+)/', api_views.SegmentsData.as_view(), name='get_start_segments_entries'),
    #url(r'^segment/filterEntries/(?P<segment_name>[a-zA-Z0-9]+)/', api_views.SegmentsFilterName.as_view(), name='filter_segments_by_name'),
    url(r'^segment/createNew/', api_views.SegmentsCreate.as_view(), name='create_segment'),
    url(r'^segment/createTemp/', api_views.SegmentsCreateTemp.as_view(), name='create_temp_segment'),

db_management/urls.py
from django.conf.urls import url
from . import views
#from django.conf.urls import *
#from django.contrib.auth import views as auth_views
#from django.views.generic import TemplateView
urlpatterns = [
    url(r'^point/$', views.ManagePoint, name='db_point'),
    url(r'^descriptions_workspace', views.ManageDescriptionWorkSpace, name='descriptions_workspace'),
    url(r'^entries_workspace', views.ManageEntriesWorkSpace, name='entries_workspace'),
    url(r'^descriptions_preview/(?P<workspace_id>[0-9]+)/', views.ManageDescriptionsPreview, name='descriptions_preview'),
    url(r'^pdf/(?P<arg1>[0-9]+)/$', views.MyPDF.as_view(), name='pdf'),
    url(r'^edit_db_record/(?P<entry_id>[0-9]+)/', views.EditDBEntrie, name='edit_db_record'),
    url(r'^test/', views.TestView, name='test_view'),
    ] 

docs/urls.py
from django.conf.urls import url
from . import views
#from django.conf.urls import *
#from django.contrib.auth import views as auth_views
#from django.views.generic import TemplateView
urlpatterns = [
    url(r'^$', views.DocsView, name='docs'),
    ] 

incidents/urls.py
from django.conf.urls import url
from . import views
#from django.conf.urls import *
#from django.contrib.auth import views as auth_views
#from django.views.generic import TemplateView
urlpatterns = [
    url(r'^$', views.ManageIncidentsView.as_view(), name='incidents'),
    ] 

main/urls.py
from django.conf.urls import url
from . import views
#from django.conf.urls import *
#from django.contrib.auth import views as auth_views
#from django.views.generic import TemplateView
urlpatterns = [
    url(r'^$', views.PointView.as_view(), name='point'),
    ] 

unamid/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.contrib.sites.models import Site
from . import views
from django.conf import settings

admin.site.unregister(Site)


urlpatterns = [
    url(r'^upload_excel/', include('oldUpload.urls', namespace="upload_excel")),
    url(r'^admin/', admin.site.urls),
    url(r'^point/', include('main.urls', namespace="main")),
    url(r'^db_manage/', include('db_management.urls', namespace="db_manage")),
    url(r'^analytics/', include('analytics.urls', namespace="analytics")),
    url(r'^docs/', include('docs.urls', namespace="docs")),
    url(r'^incidents_processing/', include('incidents.urls', namespace="incidents")),
    url(r'^', include('userena.urls')),
    url(r'^accounts/', include('accounts.urls', namespace="accounts")),
    url(r'^api/', include('api.urls', namespace="api")),
    #url(r'^uploads/uploads/(?P<path>[a-zA-Z0-9]+)', views.download, name='down'),
    url(r'^uploads/uploads/(?P<path>[a-zA-Z0-9]+.*)$', views.download)
]#(?P<path>.*)$

db_management/models.py
from __future__ import unicode_literals
import os
from django.db import models
from datetime import date, datetime, timedelta
from django.utils import timezone
from django.contrib.auth.models import User
from incidents.models import * 

# Create your models here.

class Links(models.Model):
	url = models.URLField(max_length=200, blank=True)

	class Meta:
		verbose_name = 'Entry Links'
		verbose_name_plural = "Entry Links"

	def __unicode__(self):
		return unicode(self.url)

class Document(models.Model):
    description = models.CharField(max_length=255, blank=True)
    document = models.FileField(upload_to='uploads/')
    uploaded_at = models.DateTimeField(auto_now_add=True)

    class Meta:
		verbose_name = 'Entry Documents'
		verbose_name_plural = "Entry Documents"

    def __unicode__(self):
		return unicode(self.description)

class EntryVictimsData(models.Model):
	group = models.ForeignKey('incidents.VictimClass', related_name='entry_victim_class', blank=True, null=True)
	quantity = models.IntegerField(default=0, verbose_name='Victim quantity')

	def computeNames(self):
		m = self.group.name
		result = str("%s - %s" % (m, self.quantity))
		return result	

class EntryIncidentsValue(models.Model):
	now = datetime.now()

	victims = models.ManyToManyField(EntryVictimsData, blank=True, related_name="entry_assigned_victims_data")
	date = models.DateField(auto_now=False, auto_now_add=False, blank=True, null=True, verbose_name='Entry value date') 
	time = models.TimeField(auto_now=False, auto_now_add=False, blank=True, null=True, verbose_name='Entry value time')
	actors = models.ManyToManyField('incidents.ActorsGroup', blank=True, related_name='entry_value_actors_groups')
	locations = models.ManyToManyField('incidents.Location', blank=True, related_name='entry_value_locations')
	nature = models.ManyToManyField('incidents.Nature', blank=True, related_name='entry_value_natures')	

	def convert_time(self):
		if self.time is not None:
			date = time.strftime(self.time, '%H:%M')
		else:
			m_date = time(11,0,0)
			date = time.strftime(m_date, '%H:%M')
		return date	

	def convert_date(self): 
		if self.date is not None: 
			date = datetime.strftime(self.date, '%d-%m-%Y')
		else:
			now = datetime.now()
			date = datetime.strftime(now, '%d-%m-%Y')
		return date	

class Entry(models.Model):
	name = models.CharField(max_length=255, blank=True, verbose_name='Title') #+
	creation_date = models.DateTimeField(auto_now_add=True, verbose_name='Recorded on') #+
	created_by = models.ForeignKey(User, related_name='entry_created_by', blank=True, null=True) #+
	descriptions_instances = models.ManyToManyField('incidents.IncindentDescription', blank=True, related_name="entry_assigned_descriptions")
	value_instance = models.ManyToManyField(EntryIncidentsValue, blank=True, related_name="entry_assigned_values")
	remarks = models.TextField(blank=True, help_text="Enter remarks to entry")
	JMACcomments = models.TextField(blank=True, help_text="Enter comments for entry")
	Summary = models.TextField(blank=True, help_text="Enter summary for entry")
	links = models.ManyToManyField(Links, blank=True, related_name="entry_assigned_links")
	documents = models.ManyToManyField(Document, blank=True, related_name="entry_assigned_documents")

	class Meta:
		verbose_name = 'Database Entry'

	def __unicode__(self):
		return unicode(self.name)	

	def get_name(self):
		result = self.created_by.username
		return result

	def convert_date(self):
		creation_date = datetime.strftime(self.creation_date, '%d %B %Y')
		return creation_date

db_management/templates/db_management/db_point.html
<!DOCTYPE html>
{% load staticfiles %}
<html>
<head>
  <meta charset="utf-8">
  <title>Database Management | POINT</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" type="text/css" href="{% static 'db_management/css/normalize.css' %}">
  <link rel="stylesheet" type="text/css" href="{% static 'db_management/css/webflow.css' %}">
  <link rel="stylesheet" type="text/css" href="{% static 'db_management/css/db_manage-27-06-2016-7.css' %}">
  <script src="https://ajax.googleapis.com/ajax/libs/webfont/1.4.7/webfont.js"></script>
  <script>
    WebFont.load({
      google: {
        families: ["Roboto Condensed:regular,700"]
      }
    });
  </script>
  <script type="text/javascript" src="{% static 'db_management/js/modernizr.js' %}"></script>
</head>
<body class="normal_body">
{% if request.user.is_authenticated %}
<div class="w-nav navbar">
    <a class="w-inline-block navbar__tomainlogo" href="{% url 'main:point' %}"></a>
    <div class="w-container navbar__conteiner">
      <nav class="w-nav-menu navbar__menu" role="navigation">
      <a class="w-nav-link navbar__link" href="{% url 'incidents:incidents' %}">Incident Processing</a>
      <a class="w-nav-link navbar__link active" href="{% url 'db_manage:db_point' %}">Database Management</a>
      <a class="w-nav-link navbar__link" href="{% url 'analytics:chart' %}">Create reports</a>
      <a class="w-nav-link navbar__link" href="{% url 'docs:docs' %}">User Manual</a>
      <a class="w-nav-link navbar__link" href="{% url 'userena_signout' %}">Sign out</a>
      </nav>
      <div class="w-nav-button">
        <div class="w-icon-nav-menu"></div>
      </div>
    </div>
  </div>
  <div class="additional_header">
    <div class="w-container additional_header__conteiner"><a class="additional_header__link" href="{% url 'db_manage:descriptions_workspace' %}">Incidents Collation</a><a class="additional_header__link" href="{% url 'db_manage:entries_workspace' %}">Entries Search</a>
    </div>
  </div>
<div class="content_block">
    <div class="initialstate">
      <div class="selectoptionhint">
        <h3 class="hinttext"><span class="boldspan">Please select options from the second row above.</span><br>if you want to process incidents please click <br>"<span class="underlinespan">Incidents Collation</span>".<br>If you want to search for database entries please click <br>"<span class="underlinespan">Entries Search</span>".</h3>
      </div>
    </div>
</div>    
  <!--[if lte IE 9]><script src="https://cdnjs.cloudflare.com/ajax/libs/placeholders/3.0.2/placeholders.min.js"></script><![endif]-->
{% else %}
<div class="w-container" style="background:black;">
  <div class="logo menu"></div>
  <p class="subtitle">UNAMID</p>
  <div class="w-clearfix join-wrapper">
    <div class="beta-line"></div>
    <p class="join">Please Log in</p>
    <div class="beta-line"></div>
  </div>
  <div class="optionsconteiner">
    <a class="w-button button menuoptions" href="{% url 'userena_signin' %}">Log in</a>
  </div>
</div>
{% endif %}  
</body>
</html>

db_management/templates/db_management/db_point_2.html
<!DOCTYPE html>
{% load staticfiles %}
<html>
<head>
  <meta charset="utf-8">
  <title>Database Management | POINT</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" type="text/css" href="{% static 'db_management/css/normalize.css' %}">
  <link rel="stylesheet" type="text/css" href="{% static 'db_management/css/webflow.css' %}">
  <link rel="stylesheet" type="text/css" href="{% static 'db_management/css/db_manage-27-06-2016-6.css' %}">
  <script src="https://ajax.googleapis.com/ajax/libs/webfont/1.4.7/webfont.js"></script>
  <script>
    WebFont.load({
      google: {
        families: ["Roboto Condensed:regular,700"]
      }
    });
  </script>
  <script type="text/javascript" src="{% static 'db_management/js/modernizr.js' %}"></script>
</head>
<body class="normal_body">
{% if request.user.is_authenticated %}
<div class="w-nav navbar">
    <a class="w-inline-block navbar__tomainlogo" href="{% url 'main:point' %}"></a>
    <div class="w-container navbar__conteiner">
      <nav class="w-nav-menu navbar__menu" role="navigation">
      <a class="w-nav-link navbar__link" href="{% url 'incidents:incidents' %}">Incident Processing</a>
      <a class="w-nav-link navbar__link active" href="{% url 'db_manage:db_point' %}">Database Management</a>
      <a class="w-nav-link navbar__link" href="{% url 'analytics:chart' %}">Create reports</a>
      <a class="w-nav-link navbar__link" href="{% url 'docs:docs' %}">User Manual</a>
      <a class="w-nav-link navbar__link" href="{% url 'userena_signout' %}">Sign out</a>
      </nav>
      <div class="w-nav-button">
        <div class="w-icon-nav-menu"></div>
      </div>
    </div>
  </div>
  <div class="additional_header">
    <div class="w-container additional_header__conteiner"><a class="additional_header__link" href="{% url 'db_manage:descriptions_workspace' %}">Incidents Collation</a><a class="additional_header__link" href="{% url 'db_manage:entries_workspace' %}">Entries Search</a>
    </div>
  </div>
<div class="content_block">
    <div class="initialstate">
    <h3 class="hinttext">{{test}}</h3>
      <div class="selectoptionhint">
        <h3 class="hinttext"><span class="boldspan">Please select options from the second row above.</span><br>if you want to process incidents please click <br>"<span class="underlinespan">Incidents Collation</span>".<br>If you want to search for database entries please click <br>"<span class="underlinespan">Entries Search</span>".</h3>
      </div>
    </div>
</div>    
<script type="text/javascript" src="{% static 'db_management/js/webflow.js' %}"></script>
  <!--[if lte IE 9]><script src="https://cdnjs.cloudflare.com/ajax/libs/placeholders/3.0.2/placeholders.min.js"></script><![endif]-->
{% else %}
<div class="w-container" style="background:black;">
  <div class="logo menu"></div>
  <p class="subtitle">UNAMID</p>
  <div class="w-clearfix join-wrapper">
    <div class="beta-line"></div>
    <p class="join">Please Log in</p>
    <div class="beta-line"></div>
  </div>
  <div class="optionsconteiner">
    <a class="w-button button menuoptions" href="{% url 'userena_signin' %}">Log in</a>
  </div>
</div>
{% endif %}  
</body>
</html>

db_management/templates/db_management/descriptions_workspace.html
{% load staticfiles %}
{% load render_bundle from webpack_loader %}
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>Database Management | DESCRIPTIONS</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" type="text/css" href="{% static 'db_management/css/normalize.css' %}">
  <link rel="stylesheet" type="text/css" href="{% static 'db_management/css/webflow.css' %}">
  <link rel="stylesheet" type="text/css" href="{% static 'db_management/css/db_manage-27-06-2016-7.css' %}">
  <script src="https://ajax.googleapis.com/ajax/libs/webfont/1.4.7/webfont.js"></script>
  <script type="text/javascript">
    var AppGlobal = {
      "user": "{{user}}",
      "host": "{{host}}"
    }
  </script>
  <script>
    WebFont.load({
      google: {
        families: ["Roboto Condensed:regular,700"]
      }
    });
  </script>
  <script type="text/javascript" src="{% static 'db_management/js/modernizr.js' %}"></script>
</head>
<body class="normal_body">
{% if request.user.is_authenticated %}
<div class="w-nav navbar" data-animation="default" data-collapse="medium" data-contain="1" data-duration="400">
    <a class="w-inline-block navbar__tomainlogo" href="{% url 'main:point' %}"></a>
    <div class="w-container navbar__conteiner">
      <nav class="w-nav-menu navbar__menu" role="navigation"><a class="w-nav-link navbar__link" href="{% url 'incidents:incidents' %}">Incident Processing</a><a class="w-nav-link navbar__link  active" href="{% url 'db_manage:db_point' %}">Database Management</a><a class="w-nav-link navbar__link" href="{% url 'analytics:chart' %}">Create reports</a><a class="w-nav-link navbar__link" href="{% url 'docs:docs' %}">User Manual</a><a class="w-nav-link navbar__link" href="{% url 'userena_signout' %}">Sign out</a>
      </nav>
      <div class="w-nav-button">
        <div class="w-icon-nav-menu"></div>
      </div>
    </div>
  </div>
  <div class="additional_header">
    <div class="w-container additional_header__conteiner"><a class="additional_header__link active_link" href="{% url 'db_manage:descriptions_workspace' %}">Incidents Collation</a><a class="additional_header__link" href="{% url 'db_manage:entries_workspace' %}">Entries Search</a>
    </div>
  </div>
<div class="content_block">
    <div id="descriptionsWorkspace"></div>
</div>    
{% render_bundle "decsriptions" %}
  <!--[if lte IE 9]><script src="https://cdnjs.cloudflare.com/ajax/libs/placeholders/3.0.2/placeholders.min.js"></script><![endif]-->
{% else %}
<div class="w-container" style="background:black;">
  <div class="logo menu"></div>
  <p class="subtitle">UNAMID</p>
  <div class="w-clearfix join-wrapper">
    <div class="beta-line"></div>
    <p class="join">Please Log in</p>
    <div class="beta-line"></div>
  </div>
  <div class="optionsconteiner">
    <a class="w-button button menuoptions" href="{% url 'userena_signin' %}">Log in</a>
  </div>
</div>
{% endif %}    
</body>
</html>